[package]
name = "bevy_firework"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
bytemuck = "1.14.3"
rand = "0.8.5"
bevy_utilitarian = { version = "0.1.0", path = "../bevy_utilitarian" }
bevy_xpbd_3d = { version = "0.3.0", optional = true }

[features]
default = ["physics_xbpd"]
physics_xbpd = ["dep:bevy_xpbd_3d"]
