[package]
name = "bevy_firework"
version = "0.1.0"
edition = "2021"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mbrea-c/bevy_firework"
description = "CPU-driven, batch-rendered particle system for the Bevy game engine"
keywords = ["bevy", "gamedev", "particles", "graphics"]

[dependencies]
bevy = "0.12.0"
bytemuck = "1.14.3"
rand = "0.8.5"
bevy_utilitarian = { version = "0.2.0" }
bevy_xpbd_3d = { version = "0.3.0", optional = true }

[features]
default = ["physics_xbpd"]
physics_xbpd = ["dep:bevy_xpbd_3d"]
